from fastapi import FastAPI
from app.api.v1.endpoints import sales_endpoints, inventory_endpoint
from app.infrastructure.db.session import engine
from app.infrastructure.db.models import base_model

base_model.Base.metadata.create_all(bind=engine)

# Initialize the FastAPI application with a title
app = FastAPI(title="E-commerce Admin API")

# Register the sales endpoints
# Tags help organize the autogenerated API docs
app.include_router(sales_endpoints.router, prefix="/admin/v1/sales", tags=["Sales"])

# Register the inventory endpoints
# Tags help organize the autogenerated API docs
app.include_router(inventory_endpoint.router, prefix="/admin/v1/inventory", tags=["Inventory"])